# permissions for end users to edit mcservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: minecraft-server-operator
    app.kubernetes.io/managed-by: kustomize
  name: mcserver-editor-role
rules:
- apiGroups:
  - minecraft-server.ceerdecy.com
  resources:
  - mcservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft-server.ceerdecy.com
  resources:
  - mcservers/status
  verbs:
  - get
