---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - minecraft-server.ceerdecy.com
  resources:
  - mcservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft-server.ceerdecy.com
  resources:
  - mcservers/finalizers
  verbs:
  - update
- apiGroups:
  - minecraft-server.ceerdecy.com
  resources:
  - mcservers/status
  verbs:
  - get
  - patch
  - update
